[package]
name = "box"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "linked_list"
path = "linked_list.rs"

[[bin]]
name = "binary_tree"
path = "binary_tree.rs"

[[bin]]
name = "tree"
path = "tree.rs"