[package]
name = "ray_tracing"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ray_tracing"

[dependencies]
crossbeam-channel = "0.5.14"
itertools = "0.14.0"
png = "0.17.16"
rand = { version = "0.9.0", features = [ "small_rng" ] }
