[package]
name = "probabilistic"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "probabilistic"
path = "src/main.rs"

[dependencies]
bitvec = "1.0"
rand = "0.8"

#cargo add bitvec --package probabilistic
#cargo add rand --package probabilistic