[package]
name = "unsafe_rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "unsafe_rust"
path = "main.rs"

[[bin]]
name = "read_dir"
path = "read_dir.rs"

[dependencies]
tempfile = "3.10"

#cargo add tempfile --package unsafe_rust