[package]
name = "iterators"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "iterators"
path = "iterators.rs"

[[bin]]
name = "todos"
path = "todos.rs"

[[bin]]
name = "iterator_trait"
path = "iterator_trait.rs"