[package]
name = "threads"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "threads"
path = "threads.rs"

[[bin]]
name = "channels"
path = "channels.rs"

[[bin]]
name = "shared_data"
path = "shared_data.rs"

[[bin]]
name = "atomics"
path = "atomics.rs"